### ISSUE TITLE
Docker can't write to /workspace/rf100

### ISSUE THREAD

**Issue by yeldarby** [roboflow/roboflow-100-benchmark#32]
I'm following the instructions in the Readme to download the datasets via Docker and get a `Permission denied` error:

```
~/roboflow-100-benchmark$ docker run --rm -it     -e ROBOFLOW_API_KEY=$ROBOFLOW_API_KEY     -v $(pwd)/rf100:/workspace/rf100     -v /etc/group:/etc/group:ro     -u "$(id -u):$(id -g)"     roboflow/rf100-download
Starting downloading RF100...
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-x_k8o_zd because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/workspace/scripts/download_dataset.py", line 66, in <module>
    main()
  File "/workspace/scripts/download_dataset.py", line 54, in main
    out_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/workspace/rf100/tweeter-profile'
```

**Comment by FrancescoSaverioZuppichini** [comment]
Closing due to inactivity
